# Generated by Django 2.1.2 on 2019-05-15 21:25

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField(auto_now=True)),
                ('end_date', models.DateField(auto_now=True)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uk_name', models.CharField(max_length=400)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('start_date', models.DateField(auto_now=True)),
                ('end_date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CaseFlora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.Case')),
            ],
        ),
        migrations.CreateModel(
            name='CasePathologie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.Case')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Diagnoses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('valid', models.BooleanField(default=True)),
                ('localization', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('disease_type', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('certification', models.CharField(choices=[('A', 'American Board'), ('B', 'Bachelor')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='DoctorSpeciality',
            fields=[
                ('specialty', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'Doctors specialties',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.Case')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.Doctor')),
            ],
        ),
        migrations.CreateModel(
            name='EventComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.Event')),
            ],
        ),
        migrations.CreateModel(
            name='EventDiagnos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.Diagnoses')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.Event')),
            ],
        ),
        migrations.CreateModel(
            name='FarmGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Flora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=250)),
                ('zip_code', models.CharField(max_length=15)),
                ('building', models.CharField(max_length=4)),
                ('apartment', models.CharField(max_length=5)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.City')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.Country')),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uk_name', models.CharField(max_length=400)),
                ('address', models.TextField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.Country')),
            ],
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Medicament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uk_name', models.CharField(max_length=150)),
                ('uni_name', models.CharField(max_length=150)),
                ('bio_origin', models.BooleanField()),
                ('herbal_origin', models.BooleanField()),
                ('orphan', models.BooleanField()),
                ('homeopathic', models.BooleanField()),
                ('containment', models.TextField()),
                ('pharm_form', models.TextField()),
                ('ATS_code1', models.CharField(max_length=8, null=True)),
                ('ATS_code2', models.CharField(max_length=8, null=True)),
                ('ATS_code3', models.CharField(max_length=8, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(null=True)),
                ('reg_num', models.CharField(max_length=20)),
                ('instruction_url', models.URLField()),
                ('mnn', models.CharField(choices=[('M', 'Моно'), ('C', 'Комбінований'), ('N', 'Без МНН')], max_length=1)),
                ('issuance', models.BooleanField()),
                ('description', models.CharField(max_length=500)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.Applicant')),
                ('disease', models.ManyToManyField(to='hospital.Disease')),
                ('farm_group', models.ManyToManyField(to='hospital.FarmGroup')),
                ('flora', models.ManyToManyField(to='hospital.Flora')),
                ('manufacturer', models.ManyToManyField(to='hospital.Manufacturer')),
            ],
        ),
        migrations.CreateModel(
            name='MedType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Pathologie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('surname', models.CharField(max_length=64)),
                ('patronymic', models.CharField(max_length=64)),
                ('birthday', models.DateField()),
                ('street', models.CharField(max_length=128)),
                ('city', models.CharField(max_length=64)),
                ('state', models.CharField(max_length=64)),
                ('zip_code', models.CharField(max_length=32)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('NB', 'Non_binary')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='PatientPathologie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField()),
                ('permanent', models.BooleanField(blank=True, default=None, null=True)),
                ('pathologie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.Pathologie')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.TextField()),
                ('reaction', models.CharField(max_length=150)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.Event')),
                ('medicament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.Medicament')),
            ],
        ),
        migrations.CreateModel(
            name='Substance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='medicament',
            name='med_type',
            field=models.ManyToManyField(to='hospital.MedType'),
        ),
        migrations.AddField(
            model_name='medicament',
            name='substance',
            field=models.ManyToManyField(to='hospital.Substance'),
        ),
        migrations.AddField(
            model_name='measurement',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.Patient'),
        ),
        migrations.AddField(
            model_name='eventcomment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.Patient'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='specialty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.DoctorSpeciality'),
        ),
        migrations.AddField(
            model_name='diagnoses',
            name='disease',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.Disease'),
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.Country'),
        ),
        migrations.AddField(
            model_name='casepathologie',
            name='pathologie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.Pathologie'),
        ),
        migrations.AddField(
            model_name='caseflora',
            name='flora',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.Flora'),
        ),
        migrations.AddField(
            model_name='case',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.Doctor'),
        ),
        migrations.AddField(
            model_name='case',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.Patient'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.Country'),
        ),
        migrations.AddField(
            model_name='analysis',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.Event'),
        ),
    ]
