# Generated by Django 2.2 on 2019-05-31 19:18

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_auto_20190514_1344'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('valid', models.BooleanField(default=True)),
                ('localization', models.CharField(blank=True, max_length=150, null=True)),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.Disease')),
            ],
        ),
        migrations.CreateModel(
            name='PatientPathology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField(null=True)),
                ('permanent', models.BooleanField(blank=True, default=None, null=True)),
                ('pathology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.Disease')),
            ],
        ),
        migrations.RemoveField(
            model_name='diagnoses',
            name='disease',
        ),
        migrations.RemoveField(
            model_name='eventcomment',
            name='event',
        ),
        migrations.RemoveField(
            model_name='eventcomment',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='eventdiagnos',
            name='diagnos',
        ),
        migrations.RemoveField(
            model_name='eventdiagnos',
            name='event',
        ),
        migrations.RemoveField(
            model_name='patientpathologie',
            name='pathologie',
        ),
        migrations.RemoveField(
            model_name='patientpathologie',
            name='patient',
        ),
        migrations.AlterModelOptions(
            name='case',
            options={'ordering': ['-pk']},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-pk']},
        ),
        migrations.RemoveField(
            model_name='analysis',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='analysis',
            name='event',
        ),
        migrations.RemoveField(
            model_name='analysis',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='medicament',
            name='description',
        ),
        migrations.RemoveField(
            model_name='medicament',
            name='issuance',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='event',
        ),
        migrations.AddField(
            model_name='analysis',
            name='patient',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='hospital.Patient'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='analysis',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicament',
            name='contraindication',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='medicament',
            name='indication',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='medicament',
            name='json_instruction',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='case',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='hospital.Case'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='applicant',
            name='uk_name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='case',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='caseflora',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floras', to='hospital.Case'),
        ),
        migrations.AlterField(
            model_name='event',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='hospital.Case'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='uk_name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='medicament',
            name='mnn',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('NB', 'Non binary')], max_length=1),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='quantity',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='reaction',
            field=models.CharField(max_length=256),
        ),
        migrations.DeleteModel(
            name='CasePathologie',
        ),
        migrations.DeleteModel(
            name='Diagnoses',
        ),
        migrations.DeleteModel(
            name='EventComment',
        ),
        migrations.DeleteModel(
            name='EventDiagnos',
        ),
        migrations.DeleteModel(
            name='Pathologie',
        ),
        migrations.DeleteModel(
            name='PatientPathologie',
        ),
        migrations.AddField(
            model_name='patientpathology',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.Patient'),
        ),
        migrations.AddField(
            model_name='case',
            name='diagnose',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.Diagnose'),
        ),
    ]
