# Generated by Django 2.1.2 on 2019-05-15 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_auto_20190516_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicament',
            name='mnn',
            field=models.CharField(max_length=50),
        ),
    ]
