# Generated by Django 2.1.2 on 2019-05-15 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_auto_20190516_0036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicament',
            name='description',
        ),
        migrations.RemoveField(
            model_name='medicament',
            name='issuance',
        ),
    ]
