# Generated by Django 2.1.2 on 2019-05-30 18:32

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_auto_20190516_0037'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicament',
            name='contraindication',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='medicament',
            name='indication',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='medicament',
            name='json_instruction',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
